### ISSUE TITLE
'ascii' codec can't decode byte 0xdd in position 4: ordinal not in range(128)

### ISSUE THREAD

**Issue by ethan0531** [ltguo19/VSUA-Captioning#14]
When I run cal_geometry_feats.py, this kind of mistake happens .
 BoxInfo = pickle.load(open('E://yuyimiaoshu//GCN//VSUA_Captioning_master//data//vsua_box_info.pkl','rb'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 4: ordinal not in range(128)

**Comment by ltguo19** [comment]
This is caused by [Pickle incompatibility of numpy arrays between Python 2 and 3](https://stackoverflow.com/questions/11305790/pickle-incompatibility-of-numpy-arrays-between-python-2-and-3). You should use python2 instead of python3.

**Comment by ethan0531** [comment]
Thank you. I've solved the problem
