### ISSUE TITLE
Actually, the code use two MLPs instead of GCNs for simple?

### ISSUE THREAD

**Issue by kangkang59812** [ltguo19/VSUA-Captioning#5]
While in your paper,  the process is excuted by GCNs.
![8EB42436-0459-407A-9B2D-7F14F37512CC](https://user-images.githubusercontent.com/12228641/70765972-5ade3280-1d97-11ea-9bb4-38bee160e4b9.png)

**Comment by ltguo19** [comment]
We use a similar simple formulation as in "Auto-encoding scene graphs for image captioning." "In our implementation, go,ga, and gr use the same structure with independent parameters: a concatenation operation followed by a FC-ReLU-Dropout layer."
